### PR TITLE
Add more Apache 2.4 metrics + mod_proxy metrics

### PR DESCRIPTION
**Pull request by rainerjung**
Provide additional server-status metrics. The series of commits first provide more base metrics, than also adds the metrics from mod_proxy (see also issue #47).
Test data is updated according to these new metrics.

### CODE REVIEW

**Comment by rainerjung** [comment]
Note that the build failure in circleci is not directly related to this PR. Currently all builds seem to fail. I saw the same type of failure eg. on Ubuntu 18.04., but not on CentOS 8. The test run here though succeeds.

**Comment by Lusitaniae** [comment]
Indeed, the Circle CI need some updates, has been failing for quite some time

@roidelapluie could you also have a quick look at the proposed changes if you have a minute?

**Comment by Lusitaniae** [comment]
hi @rainerjung 

Sorry for the long delay

Could you try merging master to your branch and see if the CI/CD can correctly build with your changes

**Comment by rainerjung** [comment]
Merged and checks now pass.

**Comment by frittentheke** [comment]
@rainerjung   this is really cool - thanks for adding this!
@Lusitaniae  Could this potentially be merged then?

**Comment by Lusitaniae** [comment]
Some of the additional metrics should not be tracked by Apache Exporter

https://prometheus.io/docs/instrumenting/writing_exporters/#machine-and-process-metrics

```
Machine and process metrics

Many systems, for example Elasticsearch, expose machine metrics such as CPU, memory and filesystem information. As the node exporter provides these in the Prometheus ecosystem, such metrics should be dropped.
```

**Comment by Lusitaniae** [comment]
@roidelapluie Would you like to review too?

**Comment by rainerjung** [comment]
CPU metrics: the included CPU metrics are not system wide CPU metrics. They provide only the CPU use by Apache httpd and its children. Since Apache is multi-process and the processes have dynamic live duration, it is nearly impossible to correctly monitor Apache CPU use from outside of the process. The Apache server-status has wuite complex code to track CPU for the httpd parent process plus all children plus all historic children to provide correct monotonically increasing CPU use numbers. And in fact it took until Apache version 2.4.35 in September 2018 to get it right.

The cited page https://prometheus.io/docs/instrumenting/writing_exporters/#machine-and-process-metrics contains in the next page an example - the Java exporter - that for the same reasons exports the CPU use just of the JVM process.

So IMHO the CPU metrics under discussion here are not redundant and can currently not be monitored in other ways.

**Comment by Lusitaniae** [comment]
Thank you for the extra details @rainerjung 

I will merge for now!

**Comment by frittentheke** [comment]
@Lusitaniae would you consider doing a release with this new feature in?
Also using and testing the newly refactored CI/CD (https://github.com/Lusitaniae/apache_exporter/pull/104) would be work it?

**Comment by Lusitaniae** [comment]
v0.10.0 was released yesterday, please test and let me know.

Thanks everyone.

**Comment by frittentheke** [comment]
> v0.10.0 was released yesterday, please test and let me know.
> 
> Thanks everyone.

I did. It works great in general, but I found a bug - see https://github.com/Lusitaniae/apache_exporter/issues/109

**Pull request merged**
