### PR TITLE
Reset ProxyBalancer metrics on each scrape to remove stale data

### LINKED ISSUE #109: mod_proxy metrics report stale / old data for backend status
Thanks @rainerjung for implementing mod_proxy metrics (https://github.com/Lusitaniae/apache_exporter/pull/102) - greatly appreciated.

1. 

I just updated to the new apache_exporter release (https://github.com/Lusitaniae/apache_exporter/releases/tag/v0.10.0). It works great, but unfortunately I ran into a bug with stale data on the reported state of balancer members ....

Initially the status for all backends is reported correctly, i.e.
```
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-01.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-02.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-03.example.com:7481"} 1
```

When the status changes though, the old status continues to be exported as well:
```
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Dis",worker="http://host-01.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Dis",worker="http://host-02.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Dis",worker="http://host-03.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-01.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-02.example.com:7481"} 1
apache_proxy_balancer_status{balancer="balancer://obst-balancer",status="Init Ok",worker="http://host-03.example.com:7481"} 1

```
I believe this is due to the currently reported status from the scoreboard is simply being added to exported data, but none of the old, non-current status data is ever removed in https://github.com/Lusitaniae/apache_exporter/pull/102/files#diff-fb1d52e526ddf3b580f7d8c5378ed5b4154d782c9de8da9e517b43ddf3d970fcR512

2. 

If I may raise another idea in this regard. Currently only the actual status string reported in the scoreboard is reported with value "1", but none of the others with value "0". The various status values are documented (https://httpd.apache.org/docs/trunk/howto/reverse_proxy.html#status) and looking at i.e. the node_exporter (https://www.robustperception.io/linux-software-raid-metrics-from-the-node-exporter) which reports state in this manner for i.e. `node_systemd_unit_state` or `node_md_stat`

```
node_md_state{device="md0",state="active"} 1
node_md_state{device="md0",state="inactive"} 0
node_md_state{device="md0",state="recovering"} 0
node_md_state{device="md0",state="resync"} 0
```

I know this creates more time series, but it does not waste storage with values rarely changing and it would simply aligns things style-wise.

### PR DESCRIPTION
**Pull request by frittentheke**
This should fix #109

### CODE REVIEW

**Comment by Lusitaniae** [comment]
@rainerjung if you could be so kind as to quickly review?

I'm not actively using Apache (and Proxy mode) so difficult to test by myself

**Comment by frittentheke** [comment]
@Lusitaniae  ... not saying that I don't care for what @rainerjung  thinks, but I certainly did test this myself with 

- a set of balancers configured and quite a few state changes on the balancer members
- adding and removing balancer members from the config with hot reload as well as restart

to me the metrics were not containing any stale data any more.

**Comment by Lusitaniae** [comment]
much appreciated @frittentheke

**Comment by frittentheke** [comment]
> much appreciated @frittentheke

I can only second that - thanks a bunch for accepting my change @Lusitaniae !
Would you maybe consider cutting a 0.10.1 "bugfix" release at some point then?

**Comment by Lusitaniae** [comment]
Doing that now :+1:

**Comment by roidelapluie** [comment]
I think that this fix is not correct, we should instead use a MustNewConstMetric and collect it on every scrape.

The current approach is fragile because if 2 prometheus scrape at the same time, they will get hazardous results.

**Comment by Lusitaniae** [comment]
I open a new issue for that, would you like to give it a try @frittentheke ?

**Pull request merged**
