### PR TITLE
chore(deps): Update prometheus common and exporter-toolkit

### PR DESCRIPTION
**Pull request by blkperl**
fixes #157 #158

### CODE REVIEW

**Comment by blkperl** [comment]
@Lusitaniae  I think this will fix the dependabot test failures

**Review by Lusitaniae — APPROVED** [review]

**Comment by blkperl** [comment]
@Lusitaniae is the CircleCI Pipeline step suppose to be failing? Is it okay to merge?

**Comment by Lusitaniae** [comment]
yep, it's fine we moved to GH actions in #147 

As far as I see my account in Circle still working fine, wonder if you're missing access from your account

We can cleanup Circle Ci completely

**Comment by blkperl** [comment]
@Lusitaniae oh maybe it's because I opened it from a fork.  Can you walk me through the release process? I made a tag yesterday but I see there's a version file that needs to be updated

**Pull request merged**
