### PR TITLE
Create compose.yml

### PR DESCRIPTION
**Pull request by dimaguy**

### CODE REVIEW

**Comment by Lusitaniae** [comment]
Thank you

**Comment by Lusitaniae** [comment]
Usually the default name is `docker-compose.yml` and maybe it would be good to have a short description in the readme for anyone interested?

**Comment by Lusitaniae** [comment]
ok, thanks for the update!

Will wait for the readme changes

**Comment by Lusitaniae** [comment]
thank you!

**Comment by dimaguy** [comment]
De nada, irmão :)

**Pull request merged**
