### PR TITLE
Upgrade to building with go 1.16

### PR DESCRIPTION
**Pull request by blkperl**
I'm not quite sure if I need to commit the vendor directory changes.

Should I run `go mod vendor` and commit the results to the PR?

### CODE REVIEW

**Comment by Lusitaniae** [comment]
thanks for the contribution @blkperl 

Yes, please commit the changes to vendor

**Comment by blkperl** [comment]
@Lusitaniae added!

**Comment by blkperl** [comment]
@Lusitaniae do you know what I need to do to get circleci passing?

**Comment by blkperl** [comment]
make promu and go tidy seem to undo each others changes as well.

**Comment by Lusitaniae** [comment]
Possibly need to update dependencies

There hasn't been any update there for maybe 1 or 2 years

**Comment by blkperl** [comment]
@Lusitaniae i'm not sure what you mean by that. I ran go get -u on the dependencies in the go.mod file.

**Comment by Lusitaniae** [comment]
I finally updated all the CI/CD code based on the official exporters (haproxy) and now the build is passing.

I also updated go to 1.16 in the process. Would you care to review @blkperl ?

https://github.com/Lusitaniae/apache_exporter/pull/104

If my PR solves the issue, we can close this one I guess. 

Much appreciated for the submission, hope I can be more helpful in future PRs :)

**Pull request closed without merging**
