### PR TITLE
Multistage dockerfile

### PR DESCRIPTION
**Pull request by danifernandezs**
I'm add a go container to make the binary and use the multistage support to use only one dockerfile to make apache-exporter and build the final container

### CODE REVIEW

**Comment by Lusitaniae** [comment]
@danifernandezs Please see Golang documentation in Docker at https://hub.docker.com/_/golang/

You can use this to build golang application using Docker

`docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.16 go build -v`

**Comment by danifernandezs** [comment]
@Lusitaniae it´s funny to receive in the answer the command to build with docker, the same that i do with only one dockerfile, and only one command, with the magic of multistage, stage 1 build app, stage 2 build container

**Comment by Lusitaniae** [comment]
I understand, but that's your personal need.

For the project, it's more important to be consistent with the other Prometheus exporters.

**Comment by danifernandezs** [comment]
not really my personal need

one year ago i wanted to use this exporter, found a dockerfile inside the repo, this dockerfile fails to build because he try to copy and unexisting compiled app, after that, i include a multistage dockerfile to solve this

**Pull request closed without merging**
